FROM node:11

USER node
RUN mkdir -p /home/node/packages/event-bot
WORKDIR /home/node/packages/event-bot
ADD packages/event-bot/package-lock.json /home/node/packages/event-bot
ADD packages/event-bot/package.json /home/node/packages/event-bot

ADD packages/ /home/node/packages/
ADD lerna.json /home/node/
ADD package.json /home/node/
ADD package-lock.json /home/node/
USER root
RUN chown -R node:node /home/node/
USER node

RUN npx lerna bootstrap

USER root

CMD ["node", "./index.js"]