FROM node:11

USER node
RUN mkdir -p /home/node/packages/shard
WORKDIR /home/node/packages/shard
ADD packages/shard/package-lock.json /home/node/packages/shard
ADD packages/shard/package.json /home/node/packages/shard

ADD packages/ /home/node/packages/
ADD lerna.json /home/node/
ADD package.json /home/node/
ADD package-lock.json /home/node/
USER root
RUN chown -R node:node /home/node/
USER node

RUN npx lerna bootstrap --scope=shard

USER root

CMD ["node", "./index.js"]
