FROM node:11

USER node
RUN mkdir -p /home/node/packages/worker
WORKDIR /home/node/packages/worker
ADD packages/worker/package-lock.json /home/node/packages/worker
ADD packages/worker/package.json /home/node/packages/worker

ADD packages/ /home/node/packages/
ADD lerna.json /home/node/
ADD package.json /home/node/
ADD package-lock.json /home/node/
USER root
RUN chown -R node:node /home/node/
USER node

RUN npx lerna bootstrap

USER root

CMD ["node", "./index.js"]
